# fly.toml app configuration file generated for codecourse on 2024-08-21T21:27:08+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'codecourse'
primary_region = 'waw'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[mounts]
  source = "data"
  destination = "/app/data"
  
[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
